/**
 * Demo User Configuration
 * ONLY FOR DEV/STAGING - Never use in production
 */

export const DEMO_CONFIG = {
  email: 'max.mustermann.demo@example.com',
  password: 'Demo-2025!Max',
  
  profile: {
    first_name: 'Max',
    last_name: 'Mustermann',
    date_of_birth: '1986-04-12',
    street: 'Testweg 5',
    postal_code: '10115',
    city: 'Berlin',
    phone: '+49 30 00000000',
    health_insurance: 'AOK (Demo)',
    salutation: 'Herr',
    title: null,
  },
  
  seed: 'MAX_MUSTERMANN_DEMO_SEED_2025',
  daysToGenerate: 90,
  batchSize: 200,
} as const;

export const DEMO_DOCTORS = [
  {
    salutation: 'Frau',
    title: 'Dr. med.',
    first_name: 'Jana',
    last_name: 'Beispiel',
    specialty: 'Allgemeinmedizin',
    street: 'Beispielallee 10',
    postal_code: '10115',
    city: 'Berlin',
    phone: '+49 30 00000010',
    email: 'hausarzt@example.com',
    fax: '+49 30 00000011',
  },
  {
    salutation: 'Herr',
    title: 'Dr. med.',
    first_name: 'Tim',
    last_name: 'Beispiel',
    specialty: 'Neurologie',
    street: 'Praxisplatz 3',
    postal_code: '10117',
    city: 'Berlin',
    phone: '+49 30 00000020',
    email: 'neurologie@example.com',
    fax: '+49 30 00000021',
  },
] as const;

export const DEMO_MEDICATIONS = {
  prophylaxis: [
    {
      name: 'Fremanezumab (Ajovy)',
      wirkstoff: 'Fremanezumab',
      staerke: '225 mg',
      darreichungsform: 'Injektion',
      einheit: 'Fertigspritze',
      intake_type: 'regular',
      art: 'prophylaxe',
      effect_category: 'prophylaxe',
      typical_indication: 'Migräneprophylaxe',
      hinweise: 'Prophylaxe – 1× monatlich subkutan',
      dosis_morgens: '1',
      regular_weekdays: null,
      regular_notes: 'Jeden 5. des Monats',
    },
    {
      name: 'Metoprolol',
      wirkstoff: 'Metoprolol succinat',
      staerke: '47,5 mg',
      darreichungsform: 'Retardtablette',
      einheit: 'Tablette',
      intake_type: 'regular',
      art: 'prophylaxe',
      effect_category: 'prophylaxe',
      typical_indication: 'Migräneprophylaxe',
      hinweise: 'Betablocker – täglich morgens',
      dosis_morgens: '1',
      regular_weekdays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
    },
    {
      name: 'Magnesiumcitrat',
      wirkstoff: 'Magnesium',
      staerke: '200 mg',
      darreichungsform: 'Kapsel',
      einheit: 'Kapsel',
      intake_type: 'regular',
      art: 'prophylaxe',
      effect_category: 'nahrungsergaenzung',
      typical_indication: 'Migräneprophylaxe',
      hinweise: 'Nahrungsergänzung – täglich abends',
      dosis_abends: '1',
      regular_weekdays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
    },
    {
      name: 'Eliquis',
      wirkstoff: 'Apixaban',
      staerke: '5 mg',
      darreichungsform: 'Filmtablette',
      einheit: 'Tablette',
      intake_type: 'regular',
      art: 'dauermedikation',
      effect_category: 'sonstiges',
      typical_indication: 'Antikoagulation (Demo)',
      hinweise: 'DEMO – 2× täglich (morgens + abends)',
      dosis_morgens: '1',
      dosis_abends: '1',
      regular_weekdays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
    },
  ],
  acute: [
    {
      name: 'Sumatriptan',
      wirkstoff: 'Sumatriptan',
      staerke: '50 mg',
      darreichungsform: 'Filmtablette',
      einheit: 'Tablette',
      intake_type: 'as_needed',
      art: 'bedarf',
      effect_category: 'triptan',
      typical_indication: 'Akute Migräneattacke',
      hinweise: 'Bei Migräneanfall – max. 2× in 24h',
      as_needed_standard_dose: '1 Tablette',
      as_needed_max_per_24h: 2,
      as_needed_min_interval_hours: 2,
      as_needed_max_days_per_month: 10,
    },
    {
      name: 'Ibuprofen',
      wirkstoff: 'Ibuprofen',
      staerke: '400 mg',
      darreichungsform: 'Filmtablette',
      einheit: 'Tablette',
      intake_type: 'as_needed',
      art: 'bedarf',
      effect_category: 'schmerzmittel',
      typical_indication: 'Kopfschmerzen, leichte Migräne',
      hinweise: 'Bei Bedarf – max. 3× täglich',
      as_needed_standard_dose: '1 Tablette',
      as_needed_max_per_24h: 3,
    },
    {
      name: 'Naproxen',
      wirkstoff: 'Naproxen',
      staerke: '500 mg',
      darreichungsform: 'Filmtablette',
      einheit: 'Tablette',
      intake_type: 'as_needed',
      art: 'bedarf',
      effect_category: 'schmerzmittel',
      typical_indication: 'Kopfschmerzen, Migräne',
      hinweise: 'Alternative zu Ibuprofen',
      as_needed_standard_dose: '1 Tablette',
      as_needed_max_per_24h: 2,
    },
    {
      name: 'Metoclopramid',
      wirkstoff: 'Metoclopramid',
      staerke: '10 mg',
      darreichungsform: 'Tablette',
      einheit: 'Tablette',
      intake_type: 'as_needed',
      art: 'bedarf',
      effect_category: 'antiemetikum',
      typical_indication: 'Übelkeit bei Migräne',
      hinweise: 'Bei Übelkeit – 20 Min vor Schmerzmittel',
      as_needed_standard_dose: '1 Tablette',
      as_needed_max_per_24h: 3,
    },
    {
      name: 'Diazepam',
      wirkstoff: 'Diazepam',
      staerke: '5 mg',
      darreichungsform: 'Tablette',
      einheit: 'Tablette',
      intake_type: 'as_needed',
      art: 'bedarf',
      effect_category: 'sonstiges',
      typical_indication: 'Starke Unruhe/Schlafstörung (selten)',
      hinweise: 'DEMO – nur bei starker Unruhe, selten',
      as_needed_standard_dose: '1 Tablette',
      as_needed_max_per_24h: 1,
    },
  ],
} as const;

export function isDemoEnabled(): boolean {
  // Only in DEV mode or with explicit flag
  return import.meta.env.DEV || import.meta.env.VITE_DEMO_SEED_ENABLED === 'true';
}
