// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzcbjciqrhsezxkjeyhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6Y2JqY2lxcmhzZXp4a2pleWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzUxNTIsImV4cCI6MjA2OTgxMTE1Mn0.Ak7qF9uZ7u9E48pkhlK5C4hyKQv6U5poOQAaO0K-cB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});