// This file is automatically generated. Do not edit it directly.

// ✅ HOTFIX: Re-export the SINGLE supabase client instance to avoid
// "Multiple GoTrueClient instances detected".
import { supabase as sharedSupabase, VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY } from '@/lib/supabaseClient';

export const SUPABASE_URL = VITE_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY = VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Note: keep name `supabase` for backward compatibility across the codebase.
export const supabase = sharedSupabase;

